// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: proto/db_service.proto

package db

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_db_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         int32                  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_db_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_db_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         int32                  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_db_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ValidateTokenResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                      // validacija korisnika
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // jedinstveni ID transakcije
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`                                  // iznos
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // vrijeme transakcije
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_proto_db_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{4}
}

func (x *DepositRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DepositRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DepositRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         int32                  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResponse) Reset() {
	*x = DepositResponse{}
	mi := &file_proto_db_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResponse) ProtoMessage() {}

func (x *DepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DepositResponse) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{5}
}

func (x *DepositResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *DepositResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                      // dodaj token
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // idempotency
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_proto_db_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{6}
}

func (x *WithdrawRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WithdrawRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *WithdrawRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type WithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         int32                  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	mi := &file_proto_db_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *WithdrawResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_db_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetBalanceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         int32                  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_db_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_db_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalanceResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_proto_db_service_proto protoreflect.FileDescriptor

const file_proto_db_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/db_service.proto\x12\x02db\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\x05R\x05error\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"F\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\x05R\x05error\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"\x83\x01\n" +
	"\x0eDepositRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"A\n" +
	"\x0fDepositResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\x05R\x05error\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\"\x84\x01\n" +
	"\x0fWithdrawRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"B\n" +
	"\x10WithdrawResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\x05R\x05error\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\")\n" +
	"\x11GetBalanceRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"D\n" +
	"\x12GetBalanceResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\x05R\x05error\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance2\xa7\x02\n" +
	"\tDBService\x12,\n" +
	"\x05Login\x12\x10.db.LoginRequest\x1a\x11.db.LoginResponse\x12D\n" +
	"\rValidateToken\x12\x18.db.ValidateTokenRequest\x1a\x19.db.ValidateTokenResponse\x122\n" +
	"\aDeposit\x12\x12.db.DepositRequest\x1a\x13.db.DepositResponse\x125\n" +
	"\bWithdraw\x12\x13.db.WithdrawRequest\x1a\x14.db.WithdrawResponse\x12;\n" +
	"\n" +
	"GetBalance\x12\x15.db.GetBalanceRequest\x1a\x16.db.GetBalanceResponseB\rZ\vproto/db;dbb\x06proto3"

var (
	file_proto_db_service_proto_rawDescOnce sync.Once
	file_proto_db_service_proto_rawDescData []byte
)

func file_proto_db_service_proto_rawDescGZIP() []byte {
	file_proto_db_service_proto_rawDescOnce.Do(func() {
		file_proto_db_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_db_service_proto_rawDesc), len(file_proto_db_service_proto_rawDesc)))
	})
	return file_proto_db_service_proto_rawDescData
}

var file_proto_db_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_db_service_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: db.LoginRequest
	(*LoginResponse)(nil),         // 1: db.LoginResponse
	(*ValidateTokenRequest)(nil),  // 2: db.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 3: db.ValidateTokenResponse
	(*DepositRequest)(nil),        // 4: db.DepositRequest
	(*DepositResponse)(nil),       // 5: db.DepositResponse
	(*WithdrawRequest)(nil),       // 6: db.WithdrawRequest
	(*WithdrawResponse)(nil),      // 7: db.WithdrawResponse
	(*GetBalanceRequest)(nil),     // 8: db.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 9: db.GetBalanceResponse
}
var file_proto_db_service_proto_depIdxs = []int32{
	0, // 0: db.DBService.Login:input_type -> db.LoginRequest
	2, // 1: db.DBService.ValidateToken:input_type -> db.ValidateTokenRequest
	4, // 2: db.DBService.Deposit:input_type -> db.DepositRequest
	6, // 3: db.DBService.Withdraw:input_type -> db.WithdrawRequest
	8, // 4: db.DBService.GetBalance:input_type -> db.GetBalanceRequest
	1, // 5: db.DBService.Login:output_type -> db.LoginResponse
	3, // 6: db.DBService.ValidateToken:output_type -> db.ValidateTokenResponse
	5, // 7: db.DBService.Deposit:output_type -> db.DepositResponse
	7, // 8: db.DBService.Withdraw:output_type -> db.WithdrawResponse
	9, // 9: db.DBService.GetBalance:output_type -> db.GetBalanceResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_db_service_proto_init() }
func file_proto_db_service_proto_init() {
	if File_proto_db_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_db_service_proto_rawDesc), len(file_proto_db_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_db_service_proto_goTypes,
		DependencyIndexes: file_proto_db_service_proto_depIdxs,
		MessageInfos:      file_proto_db_service_proto_msgTypes,
	}.Build()
	File_proto_db_service_proto = out.File
	file_proto_db_service_proto_goTypes = nil
	file_proto_db_service_proto_depIdxs = nil
}
