// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.6
// source: proto/idempotency_service.proto

package idempotency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdempotencyService_CheckTransaction_FullMethodName = "/idempotency.IdempotencyService/CheckTransaction"
	IdempotencyService_SaveTransaction_FullMethodName  = "/idempotency.IdempotencyService/SaveTransaction"
)

// IdempotencyServiceClient is the client API for IdempotencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Idempotency Service definicija
type IdempotencyServiceClient interface {
	CheckTransaction(ctx context.Context, in *CheckTransactionRequest, opts ...grpc.CallOption) (*CheckTransactionResponse, error)
	SaveTransaction(ctx context.Context, in *SaveTransactionRequest, opts ...grpc.CallOption) (*SaveTransactionResponse, error)
}

type idempotencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdempotencyServiceClient(cc grpc.ClientConnInterface) IdempotencyServiceClient {
	return &idempotencyServiceClient{cc}
}

func (c *idempotencyServiceClient) CheckTransaction(ctx context.Context, in *CheckTransactionRequest, opts ...grpc.CallOption) (*CheckTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTransactionResponse)
	err := c.cc.Invoke(ctx, IdempotencyService_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idempotencyServiceClient) SaveTransaction(ctx context.Context, in *SaveTransactionRequest, opts ...grpc.CallOption) (*SaveTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTransactionResponse)
	err := c.cc.Invoke(ctx, IdempotencyService_SaveTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdempotencyServiceServer is the server API for IdempotencyService service.
// All implementations must embed UnimplementedIdempotencyServiceServer
// for forward compatibility.
//
// Idempotency Service definicija
type IdempotencyServiceServer interface {
	CheckTransaction(context.Context, *CheckTransactionRequest) (*CheckTransactionResponse, error)
	SaveTransaction(context.Context, *SaveTransactionRequest) (*SaveTransactionResponse, error)
	mustEmbedUnimplementedIdempotencyServiceServer()
}

// UnimplementedIdempotencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdempotencyServiceServer struct{}

func (UnimplementedIdempotencyServiceServer) CheckTransaction(context.Context, *CheckTransactionRequest) (*CheckTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedIdempotencyServiceServer) SaveTransaction(context.Context, *SaveTransactionRequest) (*SaveTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveTransaction not implemented")
}
func (UnimplementedIdempotencyServiceServer) mustEmbedUnimplementedIdempotencyServiceServer() {}
func (UnimplementedIdempotencyServiceServer) testEmbeddedByValue()                            {}

// UnsafeIdempotencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdempotencyServiceServer will
// result in compilation errors.
type UnsafeIdempotencyServiceServer interface {
	mustEmbedUnimplementedIdempotencyServiceServer()
}

func RegisterIdempotencyServiceServer(s grpc.ServiceRegistrar, srv IdempotencyServiceServer) {
	// If the following call panics, it indicates UnimplementedIdempotencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdempotencyService_ServiceDesc, srv)
}

func _IdempotencyService_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdempotencyServiceServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdempotencyService_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdempotencyServiceServer).CheckTransaction(ctx, req.(*CheckTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdempotencyService_SaveTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdempotencyServiceServer).SaveTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdempotencyService_SaveTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdempotencyServiceServer).SaveTransaction(ctx, req.(*SaveTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdempotencyService_ServiceDesc is the grpc.ServiceDesc for IdempotencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdempotencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idempotency.IdempotencyService",
	HandlerType: (*IdempotencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTransaction",
			Handler:    _IdempotencyService_CheckTransaction_Handler,
		},
		{
			MethodName: "SaveTransaction",
			Handler:    _IdempotencyService_SaveTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/idempotency_service.proto",
}
