// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: proto/idempotency_service.proto

package idempotency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provera da li transakcija već postoji
type CheckTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTransactionRequest) Reset() {
	*x = CheckTransactionRequest{}
	mi := &file_proto_idempotency_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTransactionRequest) ProtoMessage() {}

func (x *CheckTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idempotency_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTransactionRequest.ProtoReflect.Descriptor instead.
func (*CheckTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_idempotency_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckTransactionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CheckTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	CachedBalance float64                `protobuf:"fixed64,2,opt,name=cached_balance,json=cachedBalance,proto3" json:"cached_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTransactionResponse) Reset() {
	*x = CheckTransactionResponse{}
	mi := &file_proto_idempotency_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTransactionResponse) ProtoMessage() {}

func (x *CheckTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idempotency_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTransactionResponse.ProtoReflect.Descriptor instead.
func (*CheckTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_idempotency_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTransactionResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckTransactionResponse) GetCachedBalance() float64 {
	if x != nil {
		return x.CachedBalance
	}
	return 0
}

// Čuvanje transakcije u cache
type SaveTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTransactionRequest) Reset() {
	*x = SaveTransactionRequest{}
	mi := &file_proto_idempotency_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTransactionRequest) ProtoMessage() {}

func (x *SaveTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idempotency_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTransactionRequest.ProtoReflect.Descriptor instead.
func (*SaveTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_idempotency_service_proto_rawDescGZIP(), []int{2}
}

func (x *SaveTransactionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SaveTransactionRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type SaveTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTransactionResponse) Reset() {
	*x = SaveTransactionResponse{}
	mi := &file_proto_idempotency_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTransactionResponse) ProtoMessage() {}

func (x *SaveTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idempotency_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTransactionResponse.ProtoReflect.Descriptor instead.
func (*SaveTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_idempotency_service_proto_rawDescGZIP(), []int{3}
}

func (x *SaveTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_idempotency_service_proto protoreflect.FileDescriptor

const file_proto_idempotency_service_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/idempotency_service.proto\x12\vidempotency\"Y\n" +
	"\x17CheckTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"Y\n" +
	"\x18CheckTransactionResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12%\n" +
	"\x0ecached_balance\x18\x02 \x01(\x01R\rcachedBalance\"r\n" +
	"\x16SaveTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\"3\n" +
	"\x17SaveTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd3\x01\n" +
	"\x12IdempotencyService\x12_\n" +
	"\x10CheckTransaction\x12$.idempotency.CheckTransactionRequest\x1a%.idempotency.CheckTransactionResponse\x12\\\n" +
	"\x0fSaveTransaction\x12#.idempotency.SaveTransactionRequest\x1a$.idempotency.SaveTransactionResponseB\x1fZ\x1dproto/idempotency;idempotencyb\x06proto3"

var (
	file_proto_idempotency_service_proto_rawDescOnce sync.Once
	file_proto_idempotency_service_proto_rawDescData []byte
)

func file_proto_idempotency_service_proto_rawDescGZIP() []byte {
	file_proto_idempotency_service_proto_rawDescOnce.Do(func() {
		file_proto_idempotency_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_idempotency_service_proto_rawDesc), len(file_proto_idempotency_service_proto_rawDesc)))
	})
	return file_proto_idempotency_service_proto_rawDescData
}

var file_proto_idempotency_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_idempotency_service_proto_goTypes = []any{
	(*CheckTransactionRequest)(nil),  // 0: idempotency.CheckTransactionRequest
	(*CheckTransactionResponse)(nil), // 1: idempotency.CheckTransactionResponse
	(*SaveTransactionRequest)(nil),   // 2: idempotency.SaveTransactionRequest
	(*SaveTransactionResponse)(nil),  // 3: idempotency.SaveTransactionResponse
}
var file_proto_idempotency_service_proto_depIdxs = []int32{
	0, // 0: idempotency.IdempotencyService.CheckTransaction:input_type -> idempotency.CheckTransactionRequest
	2, // 1: idempotency.IdempotencyService.SaveTransaction:input_type -> idempotency.SaveTransactionRequest
	1, // 2: idempotency.IdempotencyService.CheckTransaction:output_type -> idempotency.CheckTransactionResponse
	3, // 3: idempotency.IdempotencyService.SaveTransaction:output_type -> idempotency.SaveTransactionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_idempotency_service_proto_init() }
func file_proto_idempotency_service_proto_init() {
	if File_proto_idempotency_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_idempotency_service_proto_rawDesc), len(file_proto_idempotency_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_idempotency_service_proto_goTypes,
		DependencyIndexes: file_proto_idempotency_service_proto_depIdxs,
		MessageInfos:      file_proto_idempotency_service_proto_msgTypes,
	}.Build()
	File_proto_idempotency_service_proto = out.File
	file_proto_idempotency_service_proto_goTypes = nil
	file_proto_idempotency_service_proto_depIdxs = nil
}
